---
abstract: 'Safe-navigation for Perl'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  Test2::V0: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.041, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PerlX-SafeNav
provides:
  PerlX::SafeNav:
    file: lib/PerlX/SafeNav.pm
    version: '0.004'
  PerlX::SafeNav::ArrayRef:
    file: lib/PerlX/SafeNav.pm
  PerlX::SafeNav::HashRef:
    file: lib/PerlX/SafeNav.pm
  PerlX::SafeNav::Object:
    file: lib/PerlX/SafeNav.pm
  safenav:
    file: lib/safenav.pm
requires:
  Exporter: '0'
  Tie::Array: '0'
  Tie::Hash: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gugod/PerlX-SafeNav/issues
  repository: https://github.com/gugod/PerlX-SafeNav.git
version: '0.004'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: MIT
x_static_install: '1'
